server:
  port: 8081

spring:
  application:
    name: commerce-service
  
  # Configuração do banco de dados
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/veiculosdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configuração JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        # Configurações InnoDB para garantir ACID
        storage_engine: innodb
    database-platform: org.hibernate.dialect.MySQLDialect

# Configuração do OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Configurações específicas do serviço de comércio
commerce:
  cart:
    # Tempo de validade do carrinho em milissegundos (1 minuto)
    timeout: 60000
  vehicle:
    # Cores permitidas para os veículos
    allowed-colors:
      - BRANCA
      - PRATA
      - PRETA

# Configurações de Produção vs Desenvolvimento
spring.profiles.active: ${SPRING_PROFILES_ACTIVE:dev}

---
# Perfil de Desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  
  # Configurações específicas para desenvolvimento
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# Perfil de Produção
spring:
  config:
    activate:
      on-profile: prod
  
  # Configurações específicas para produção
  jpa:
    show-sql: false 