server:
  port: 8080

spring:
  application:
    name: ui-service
  
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

# Configurações dos serviços externos
service:
  auth:
    url: http://auth-service:8082
  commerce:
    url: http://commerce-service:8081

# Configurações de segurança
security:
  cookie:
    name: JSESSIONID
    max-age: 3600 